apiVersion: v1
kind: Pod
metadata:
  name: mem-limits
spec:
  containers:
  - name: mem-demo
    image: vish/stress
    resources:
      limits:
        memory: "120Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args:
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "150M"
      - "--vm-hang"
      - "1"